### ISSUE TITLE
Registering new device type

### ISSUE THREAD

**Issue by Dogmans** [Agile-IoT/agile-stack#55]
I have implemented a new HumiTemp BLE device but registering it throws the following error:

10:16:30.817 [Thread-1] DEBUG o.e.a.devicefactory.DeviceFactoryImp - The Constructor was loaded
10:16:30.817 [Thread-1] ERROR o.e.a.devicefactory.DeviceFactoryImp - Instantiation Exception occured
java.lang.InstantiationException: null
at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.eclipse.agail.devicefactory.DeviceFactoryImp.getDevice(DeviceFactoryImp.java:337)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

Code can be found here:

https://github.com/airex-tech/agile-core/blob/humitemp/org.eclipse.agail.DeviceFactory/src/main/java/org/eclipse/agail/device/instance/HumiTempDevice.java

Is there a straightforward way of debugging this to understand what needs to be changed? Thanks!

**Comment by Dogmans** [comment]
This is now working; issue is that I was basing my code on an abstract class. It was more instructive to copy the sensor tag implementation rather than HexiwearDevice, which I think is designed to be inherited from.
